# Generated by Django 5.0.3 on 2024-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_support_description_remove_support_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporttranslation',
            name='name',
            field=models.CharField(default='support', max_length=100),
            preserve_default=False,
        ),
    ]
