# Generated by Django 5.0.3 on 2024-05-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_order_email_order_pickup_time_order_room_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Included',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
