# Generated by Django 5.0.3 on 2024-06-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_alter_included_options_alter_langtour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
