# Generated by Django 5.0.3 on 2024-06-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_alter_order_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transfer',
        ),
    ]
