# Generated by Django 5.0.3 on 2024-06-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_remove_order_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
