# Generated by Django 5.0.3 on 2024-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='meta_desc_en',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_desc_es',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meta_desc_ru',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
