# Generated by Django 5.0.3 on 2024-07-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_tour_meta_desc_en_tour_meta_desc_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='meta_desc_en',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meta_desc_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meta_desc_ru',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title_ru',
        ),
    ]
