# Generated by Django 5.0.3 on 2024-07-15 05:43

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0004_alter_city_options_city_is_published"),
        ("country", "0002_alter_country_options"),
        ("tour", "0023_remove_tour_meta_desc_en_remove_tour_meta_desc_es_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="adult_price",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="author",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="cat",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="child_price",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="children_possible",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="city",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="country",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="faqs",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="group_size",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="included",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="lang",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="meta_desc",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="notincluded",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="pregnant_possible",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="promotions",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="take",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="time_create",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="time_update",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="title",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="transfer",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="type",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="usage_policy",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="what_age_child_free",
        ),
        migrations.CreateModel(
            name="TourTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language_code", models.CharField(db_index=True, max_length=15, verbose_name="Language")),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("meta_desc", models.TextField(blank=True, db_index=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, db_index=True)),
                ("adult_price", models.IntegerField(blank=True, null=True)),
                ("child_price", models.IntegerField(blank=True, null=True)),
                (
                    "children_possible",
                    models.BooleanField(default=False, null=True, verbose_name="Возможно ли посещение с детьми?"),
                ),
                (
                    "what_age_child_free",
                    models.IntegerField(blank=True, null=True, verbose_name="До скольки лет дети бесплатно?"),
                ),
                (
                    "pregnant_possible",
                    models.BooleanField(default=False, null=True, verbose_name="Возможно ли посещение беременным?"),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="photos/%Y/%m/%d/")),
                (
                    "usage_policy",
                    models.TextField(
                        blank=True,
                        default="\n        После подтверждения вашего бронирования, вам на указанную почту или месенжер придет письмо с ваучером. В нем будут указаны все данные: наши реквизиты, так же все ваши данные указанные при бронировании. Оператор подтвердит ваше время заблаговременно. Пожалуйста, выходите в лобби отеля (место пикапа) за 10 минут до назначенного времени!\n        В день когда вас будут забирать с вашего места проживания на экскурсию, вы можете предъявить водителю распечатанный или мобильный ваучер показав его прямо на телефоне. Ваучер действителен только в указанные дату и время тура.\n        Трансфер осуществляется в обе стороны с вашего отеля! С дальних районов взимается дополнительная плата за частный трансфер который и оплачивается непосредственно оператору.",
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("is_published", models.IntegerField(choices=[(0, "Черновик"), (1, "Опубликовано")], default=0)),
                ("group_size", models.IntegerField(blank=True, null=True)),
                ("average_rating", models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ("promotions", models.BooleanField(default=False, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="tours", to="tour.category"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tours", to="city.city"
                    ),
                ),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="country.country")),
                ("faqs", models.ManyToManyField(blank=True, related_name="faqs", to="tour.faq")),
                ("included", models.ManyToManyField(blank=True, to="tour.included", verbose_name="Включено в тур")),
                ("lang", models.ManyToManyField(blank=True, related_name="lang", to="tour.langtour")),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="tour.tour",
                    ),
                ),
                (
                    "notincluded",
                    models.ManyToManyField(blank=True, to="tour.notincluded", verbose_name="Не включено в тур"),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="tags", to="tour.tagtour", verbose_name="Теги"),
                ),
                ("take", models.ManyToManyField(blank=True, to="tour.take", verbose_name="Что взять с собой")),
                (
                    "transfer",
                    models.ManyToManyField(blank=True, to="tour.transfer", verbose_name="Какой трансфер предусмотрен?"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tour.type", verbose_name="Тип поездки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Экскурсию Translation",
                "db_table": "tour_tour_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
