# Generated by Django 5.0.3 on 2024-07-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0024_remove_tour_adult_price_remove_tour_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourtranslation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='group_size',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='included',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='notincluded',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='take',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='tourtranslation',
            name='type',
        ),
    ]
