# Generated by Django 5.0.3 on 2024-07-15 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_alter_city_options_city_is_published'),
        ('country', '0002_alter_country_options'),
        ('tour', '0025_remove_tourtranslation_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tour.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='city.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='faqs',
            field=models.ManyToManyField(blank=True, related_name='faqs', to='tour.faq'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.ManyToManyField(blank=True, to='tour.included', verbose_name='Включено в тур'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='lang',
            field=models.ManyToManyField(blank=True, related_name='lang', to='tour.langtour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='notincluded',
            field=models.ManyToManyField(blank=True, to='tour.notincluded', verbose_name='Не включено в тур'),
        ),
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tour.tagtour', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='tour',
            name='take',
            field=models.ManyToManyField(blank=True, to='tour.take', verbose_name='Что взять с собой'),
        ),
        migrations.AddField(
            model_name='tour',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='transfer',
            field=models.ManyToManyField(blank=True, to='tour.transfer', verbose_name='Какой трансфер предусмотрен?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tour.type', verbose_name='Тип поездки'),
            preserve_default=False,
        ),
    ]
