# Generated by Django 5.0.3 on 2024-07-16 04:28

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0026_tour_cat_tour_city_tour_country_tour_faqs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='name',
        ),
        migrations.CreateModel(
            name='TakeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Взять с собой')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tour.take')),
            ],
            options={
                'verbose_name': 'Взять с собой Translation',
                'db_table': 'tour_take_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
