# Generated by Django 5.0.3 on 2024-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0027_remove_take_name_taketranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='take',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tour.take', verbose_name='Что взять с собой'),
        ),
    ]
