# Generated by Django 5.0.3 on 2024-07-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0030_remove_faq_answer_remove_faq_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourtranslation',
            name='slug',
        ),
    ]
