# Generated by Django 5.0.3 on 2024-07-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0031_remove_tourtranslation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='adult_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tour',
            name='child_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='children_possible',
            field=models.BooleanField(default=False, null=True, verbose_name='Возможно ли посещение с детьми?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='pregnant_possible',
            field=models.BooleanField(default=False, null=True, verbose_name='Возможно ли посещение беременным?'),
        ),
        migrations.AddField(
            model_name='tour',
            name='promotions',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(default='fsdfd', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='what_age_child_free',
            field=models.IntegerField(blank=True, null=True, verbose_name='До скольки лет дети бесплатно?'),
        ),
    ]
