# Generated by Django 5.0.3 on 2024-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_tour_city_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
