# Generated by Django 5.0.3 on 2024-05-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
