# Generated by Django 5.0.3 on 2024-04-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_alter_order_options_order_full_name_order_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tour.tour'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='tour.tour'),
        ),
    ]
