# Generated by Django 5.0.3 on 2024-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_included_notincluded_take'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='not_included',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='take_with_you',
        ),
        migrations.AddField(
            model_name='tour',
            name='notincluded',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='take',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True),
        ),
    ]
