# Generated by Django 5.0.3 on 2024-06-09 15:57

import tour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_needhelp_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tour.models.get_upload_path),
        ),
    ]
