# Generated by Django 5.0.3 on 2024-07-12 17:03

import datetime
import django.db.models.deletion
import django.utils.timezone
import tour.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_city_description_en_city_meta_desc_en_and_more'),
        ('country', '0001_initial'),
        ('tour', '0019_tour_video_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Частый вопрос', 'verbose_name_plural': 'Частые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='langtour',
            options={'verbose_name': 'язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='notincluded',
            options={'verbose_name': 'Не включено в тур', 'verbose_name_plural': 'Не включено в тур'},
        ),
        migrations.AlterModelOptions(
            name='tagtour',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Экскурсию', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Трансфер', 'verbose_name_plural': 'Трансферы'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип экскурсии', 'verbose_name_plural': 'Тип экскурсий'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='video_link',
        ),
        migrations.AddField(
            model_name='order',
            name='cash_on_tour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programm',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programm',
            name='individual_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programm',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='tour.type'),
        ),
        migrations.AddField(
            model_name='tour',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 7, 12, 17, 3, 40, 318310, tzinfo=datetime.timezone.utc), upload_to=tour.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programm',
            name='adult_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programm',
            name='child_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='take',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Взять с собой'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='children_possible',
            field=models.BooleanField(default=False, null=True, verbose_name='Возможно ли посещение с детьми?'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='included',
            field=models.ManyToManyField(blank=True, to='tour.included', verbose_name='Включено в тур'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AlterField(
            model_name='tour',
            name='notincluded',
            field=models.ManyToManyField(blank=True, to='tour.notincluded', verbose_name='Не включено в тур'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='pregnant_possible',
            field=models.BooleanField(default=False, null=True, verbose_name='Возможно ли посещение беременным?'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tour.tagtour', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='take',
            field=models.ManyToManyField(blank=True, to='tour.take', verbose_name='Что взять с собой'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='transfer',
            field=models.ManyToManyField(blank=True, to='tour.transfer', verbose_name='Какой трансфер предусмотрен?'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.type', verbose_name='Тип поездки'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='usage_policy',
            field=models.TextField(blank=True, default='\n    После подтверждения вашего бронирования, вам на указанную почту или месенжер придет письмо с ваучером. В нем будут указаны все данные: наши реквизиты, так же все ваши данные указанные при бронировании. Оператор подтвердит ваше время заблаговременно. Пожалуйста, выходите в лобби отеля (место пикапа) за 10 минут до назначенного времени!\n    В день когда вас будут забирать с вашего места проживания на экскурсию, вы можете предъявить водителю распечатанный или мобильный ваучер показав его прямо на телефоне. Ваучер действителен только в указанные дату и время тура. \n    Трансфер осуществляется в обе стороны с вашего отеля! С дальних районов взимается дополнительная плата за частный трансфер который и оплачивается непосредственно оператору.'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='what_age_child_free',
            field=models.IntegerField(blank=True, null=True, verbose_name='До скольки лет дети бесплатно?'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
            options={
                'verbose_name': 'район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
            options={
                'verbose_name': 'отель',
                'verbose_name_plural': 'Отели',
            },
        ),
    ]
