# Generated by Django 5.0 on 2024-03-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('meta_desc', models.TextField(blank=True, db_index=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_index=True)),
                ('currency_prefix', models.CharField(blank=True, default='$', max_length=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/country/')),
            ],
        ),
    ]
