# Generated by Django 5.0.3 on 2024-07-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
    ]
