# Generated by Django 5.0.3 on 2024-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description_en',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_desc_en',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
