INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Iberostar Bellevue', 'Bečići, Budva 85310, Montenegro', '033 425 100', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Eurostars Queen of Montenegro', 'Narodnog Fronta, Bečići 85310, Montenegro', '033 685 000', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Splendid Conference & Spa Resort', 'Bečići bb, Budva 85310, Montenegro', '033 773 777', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Avala Resort & Villas', '7RHP+C3G, Mediteranska, Budva, Montenegro', '033 441 000', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Tara', 'Bečići BB, Boreti, Montenegro', '033 404 196', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Montenegro Beach Resort', 'Bečići BB, Bečići 85316, Montenegro', '033 773 777', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Aleksandar', '1 Veljka Vlahovića, Budva, Montenegro', '033 402 456', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Mediteran', 'Bečići, Montenegro', '033 689 000', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Mogren', 'Slovenska Obala, Budva, Montenegro', '033 402 456', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Fineso', '11 3. Jula, Budva, Montenegro', '033 454 120', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Sanja former Olivia', '16 Velji Vinogradi, Budva 85310, Montenegro', '069 551 769', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Admiral 4 star hotel', '7RQX+89C, Jadranski put, Budva, Montenegro', '033 459 263', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Bip', '2 Veljka Vlahovića, Budva 85310, Montenegro', '069 222 072', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Garni Hotel MB', 'XIII ulica br 11, Budva 85310, Montenegro', '068 212 023', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Vila Lux', 'E65, Budva, Montenegro', '069 240 727', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Magnolija', 'Bečići 85310, Montenegro', '068 011 266', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Oaza', '27 Slovenska Obala, Budva 85310, Montenegro', '069 024 756', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Alexandar Montenegro Luxury Suites & Spa', 'Gospoština 62, 85310, Budva, Montenegro', '033 452 360', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Grbalj', 'bb Trg Sunca, Budva 85310, Montenegro', '033 452 300', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Šajo', 'bb Jadranski put, Budva 85310, Montenegro', '033 460 243', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Spa Resort Becici', '107 Ive Lole Ribara, Bečići 85316, Montenegro', '069 225 907', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Garni Hotel Mena', '7RRW+5RV, Budva 85310, Montenegro', '033 459 310', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Azzuro Apartments Budva', 'Mainski put, Budva, Montenegro', '069 356 580', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Garni Hotel Koral', 'bb 4. Proleterske, Budva 85310, Montenegro', '033 402 070', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Aparthotel Shine', 'Bečići b.b, Bečići 85316, Montenegro', '067 206 803', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Max Prestige', 'bb Žrtava Fašizma, Budva, Montenegro', '033 458 330', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Anita', '7VM8+4H6, Bečići, Montenegro', '033 471 777', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Ponta Nova', 'Rafailovici, 7VHJ+7V8, Budva 85315, Montenegro', '033 471 045', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Astoria', '4 Njegoševa, Budva 85310, Montenegro', '033 451 110', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Slovenska Plaža', 'HG Budvanska rivijera, 85310 1, Trg Slobode, Budva, Montenegro', '033 402 456', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Villa Perla Di Mare', 'br 62 Mainski put, Budva 85310, Montenegro', '068 414 014', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Budva', 'Slovenska Obala, Budva 85310, Montenegro', '033 422 000', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Sun Hostel', '68, Ferona, Budva, Montenegro', '064 1121040', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Blue Star', '11 Mainski put, Budva, Montenegro', '033 773 777', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Maestral Resort & Casino', 'Pržno, Sveti Stefan Budva, Pržno 85315, Montenegro', '033 410 100', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('SH', 'Ul, 25 Vuka Karadžića, Budva 85310, Montenegro', '067604', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Guest House Vila Bak', '7 Petrovačka, Budva 85310, Montenegro', '068 068 123', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Studio Apartments 6 Palmi', '1 Topliški Put, Budva 85310, Montenegro', '068 766 825', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Guest House Mrvaljević', '53 Topliški Put, Budva 85310, Montenegro', '069 705 281', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Aqua Breeze Apartments', '6 Praška, Budva, Montenegro', '067 734 549', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Vojinovic Apartments', '10 Ulica V, Budva, Montenegro', '068 642 026', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Apartments Danigo', 'VIII Street, Building number 16, Budva 85310, Montenegro', '069 333 122', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Villa Tortuga', 'Prijevor bb, 7RP7+R8Q, Budva 85310, Montenegro', '067 424 844', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Guesthouse Villa Antonioli', 'Njegoseva 3, entrance from St Vrzdak 4, Budva 85310, Montenegro', '068 579 429', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Le Marc Guesthouse', 'XVI ulica br14, Budva 85310, Montenegro', '067 582 274', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Apartments Dali', '29 Novembra, 37 Budva Budva County, Budva 85310, Montenegro', '068 238 148', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Aurora Old Town Apartments', '4 Vranjak, Budva 85310, Montenegro', '067 444 464', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Apartments Raičević', 'bb Solidarnosti, Budva 85310, Montenegro', '068 033 826', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('ApartmentsJovanaa', '7RRV+4C4, Budva, Montenegro', '068 335 727', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Apartmani Željko Vujović', '20 Topliški Put, Budva, Montenegro', '067 301 365', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Apartman Bećir', 'ul, 7 Solidarnosti, Budva 85310, Montenegro', '069 477 321', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Lilian Apartments', 'Ulica, 4 Solidarnosti, Budva 85310, Montenegro', '069 633 977', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Villa Spas', 'Komoševa b.b., Brdo Spas, 7RHJ+CG4, Budva 85310, Montenegro', '069 831 956', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Premier', '4 Ulica Alekse Šantića, Budva 85310, Montenegro', '068 500 015', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Apartments Ant', '14 Sremskog Fronta, Budva 85310, Montenegro', '069 129 123', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Apartmani Jovan', 'XIII ulica broj 11 Budva, Budva 85310, Montenegro', '068 212 023', '2', '2', '6');
INSERT INTO tour_hotel (name, address, phone_number, country_id, city_id, area_id) VALUES ('Hotel Aqua Doria', 'Babilonija 112, Budva 85310, Montenegro', '068 454 001', '2', '2', '6');
