# Generated by Django 5.0.3 on 2024-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('link_whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('link_telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('link_viber', models.CharField(blank=True, max_length=100, null=True)),
                ('link_facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('link_instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('link_youtube', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
